# see AvoidanceParameters description in avoidance_module_data.hpp for description.
/**:
  ros__parameters:
    avoidance:
      resample_interval_for_planning: 0.1             # [m]
      resample_interval_for_output: 1.0                # [m]
      detection_area_right_expand_dist: 0.0             # [m]
      detection_area_left_expand_dist: 0.0              #1.0 [m]
      drivable_area_right_bound_offset: 0.0             # [m]
      drivable_area_left_bound_offset: 0.0              # [m]
      object_envelope_buffer: 0.4                      # [m]

      # avoidance module common setting
      enable_bound_clipping: true
      enable_avoidance_over_same_direction: true
      enable_avoidance_over_opposite_direction: false
      enable_update_path_when_object_is_gone: true
      enable_force_avoidance_for_stopped_vehicle: true
      enable_safety_check: false
      enable_yield_maneuver: true
      disable_path_update: false

      # for debug
      publish_debug_marker: false
      print_debug_info: false

      # avoidance is performed for the object type with true
      target_object:
        car: false
        truck: false
        bus: false
        trailer: false
        unknown: true
        bicycle: false
        motorcycle: false
        pedestrian: false

      # For target object filtering
      target_filtering:
        # filtering moving objects
        threshold_speed_object_is_stopped: 1.0          # [m/s]
        threshold_time_object_is_moving: 1.0            # [s]
        threshold_time_force_avoidance_for_stopped_vehicle: 10.0 # [s]
        # detection range
        object_check_force_avoidance_clearance: 0.4    # [m]
        object_check_forward_distance: 16.5            # [m]
        object_check_backward_distance: 0.0             # [m]
        object_check_goal_distance: 16.5                # [m]
        # filtering parking objects
        threshold_distance_object_is_on_center: 0.0     # [m]
        object_check_shiftable_ratio: 0.4               # [-]
        object_check_min_road_shoulder_width: 0.1       # [m]
        # lost object compensation
        object_last_seen_threshold: 2.0

      # For safety check
      safety_check:
        safety_check_backward_distance: 0.5            # [m]
        safety_check_time_horizon: 0.4                  # [s]
        safety_check_idling_time: 0.15                    # [s]
        safety_check_accel_for_rss: 0.1                  # [m/ss]
        safety_check_hysteresis_factor: 0.2              # [-]

      # For avoidance maneuver
      avoidance:
        # avoidance lateral parameters
        lateral:
          lateral_collision_margin: 0.1                 #1.0 [m]
          lateral_collision_safety_buffer: 0.30         #0.7 [m]
          lateral_passable_safety_buffer: 0.0           # [m]
          road_shoulder_safety_margin: 0.2             #0.3 [m]
          avoidance_execution_lateral_threshold: 0.1
          max_right_shift_length: 3.5
          max_left_shift_length: 3.5
        # avoidance distance parameters
        longitudinal:
          prepare_time: 0.2                             # [s]
          longitudinal_collision_safety_buffer: 0.1    # [m]
          min_prepare_distance: 0.1                    # [m]
          min_avoidance_distance: 0.1                  # [m]
          min_nominal_avoidance_speed: 0.5              # [m/s]
          min_sharp_avoidance_speed: 0.1                # [m/s]

      # For yield maneuver
      yield:
        yield_velocity: 1.2                            #2.78 [m/s]

      # For stop maneuver
      stop:
        min_distance: 10.0                              # [m]
        max_distance: 20.0                              # [m]

      constraints:
        # vehicle slows down under longitudinal constraints
        use_constraints_for_decel: false                # [-]

        # lateral constraints
        lateral:
          nominal_lateral_jerk: 0.2                     # [m/s3]
          max_lateral_jerk: 1.0                         # [m/s3]

        # longitudinal constraints
        longitudinal:
          nominal_deceleration: -1.0                    # [m/ss]
          nominal_jerk: 0.5                             # [m/sss]
          max_deceleration: -1.78                       # [m/ss]
          max_jerk: 1.0
          # For prevention of large acceleration while avoidance
          min_avoidance_speed_for_acc_prevention: 0.5   # [m/s]
          max_avoidance_acceleration: 0.5               # [m/ss]

      target_velocity_matrix:
        col_size: 2
        matrix:
          [1.08, 1.58,                                  # velocity [m/s]
           0.50, 1.00]                                  # margin [m]
